# Generated by Django 6.1.1 on 2026-09-20 15:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المؤسسة")),
                (
                    "institution_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="نوع المؤسسة",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="رمز المؤسسة",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="العنوان"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="المدينة / الولاية",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مؤسسة",
                "verbose_name_plural": "المؤسسات",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "مدير النظام"),
                            ("INSPECTOR", "مفتش التكوين والتعليم المهنيين"),
                        ],
                        default="INSPECTOR",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="InspectionReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان المرجع"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="مرجع مشترك"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="private_references",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المالك",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرجع تفتيش",
                "verbose_name_plural": "مراجع التفتيش",
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان الدليل"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_guides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guides",
                        to="inspection.inspectionreference",
                        verbose_name="المرجع المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "دليل تفتيش",
                "verbose_name_plural": "أدلة التفتيش",
            },
        ),
        migrations.CreateModel(
            name="PrivateReferenceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "قيد المراجعة"),
                            ("APPROVED", "مقبول (معمم)"),
                            ("REJECTED", "مرفوض"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "submission_snapshot",
                    models.JSONField(verbose_name="لقطة المحتوى المرفوع"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "private_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="inspection.inspectionreference",
                        verbose_name="المرجع الخاص",
                    ),
                ),
                (
                    "resulting_shared_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_from_submissions",
                        to="inspection.inspectionreference",
                        verbose_name="المرجع المشترك الناتج",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_references",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المقترح",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب تعميم مرجع",
                "verbose_name_plural": "طلبات تعميم المراجع",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferenceNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("BRANCH", "فرع / قسم"),
                            ("SPECIFICATION", "وصف / مواصفة"),
                            ("CHECKLIST_ITEM", "بند تفتيش"),
                        ],
                        default="CHECKLIST_ITEM",
                        max_length=20,
                        verbose_name="نوع العقدة",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="الوصف / المواصفة"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="inspection.referencenode",
                        verbose_name="العقدة الأب",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="inspection.inspectionreference",
                        verbose_name="المرجع",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقدة مرجعية",
                "verbose_name_plural": "عقد مرجعية",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(verbose_name="تاريخ الزيارة")),
                (
                    "source_reference_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="اسم المرجع عند الإنشاء",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "مسودة"), ("COMPLETED", "مكتملة")],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="حالة الزيارة",
                    ),
                ),
                (
                    "frozen_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="لقطة المرجع المجمدة"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المفتش",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="inspection.institution",
                        verbose_name="المؤسسة",
                    ),
                ),
                (
                    "source_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to="inspection.inspectionreference",
                        verbose_name="المرجع المصدر",
                    ),
                ),
            ],
            options={
                "verbose_name": "زيارة تفتيشية",
                "verbose_name_plural": "الزيارات التفتيشية",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="عنوان التكليف الرسمية"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="تفاصيل التكليف"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("ISSUED", "صادر"),
                            ("REVOKED", "ملغى"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="حالة التكليف",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإصدار"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإلغاء"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(blank=True, verbose_name="سبب الإلغاء"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أُلغي بواسطة",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="inspection.visit",
                        verbose_name="الزيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تكليف رسمي",
                "verbose_name_plural": "التكليفات الرسمية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_node_id",
                    models.UUIDField(verbose_name="معرف العقدة المستهدفة"),
                ),
                (
                    "scope_locked",
                    models.BooleanField(
                        default=False, verbose_name="مقفل النطاق (ممنوع الاستبعاد)"
                    ),
                ),
                (
                    "completion_required",
                    models.BooleanField(default=False, verbose_name="إلزامي الإكمال"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="inspection.assignment",
                        verbose_name="التكليف",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيد تكليف",
                "verbose_name_plural": "قيود التكليفات",
                "unique_together": {("assignment", "target_node_id")},
            },
        ),
        migrations.CreateModel(
            name="GuideEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_node_id",
                    models.UUIDField(verbose_name="معرف العقدة المستهدفة"),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="inspection.guide",
                        verbose_name="الدليل",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر دليل",
                "verbose_name_plural": "عناصر الأدلة",
                "unique_together": {("guide", "target_node_id")},
            },
        ),
        migrations.CreateModel(
            name="VisitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="معرف العقدة المستقر"
                    ),
                ),
                (
                    "parent_node_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="معرف العقدة الأب"
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("BRANCH", "فرع / قسم"),
                            ("SPECIFICATION", "وصف / مواصفة"),
                            ("CHECKLIST_ITEM", "بند تفتيش"),
                        ],
                        default="CHECKLIST_ITEM",
                        max_length=20,
                        verbose_name="نوع العقدة",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="الوصف / المواصفة"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False, verbose_name="محدد ضمن نطاق التفتيش"
                    ),
                ),
                (
                    "is_excluded",
                    models.BooleanField(
                        default=False, verbose_name="مستبعد (Soft Exclusion)"
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("LEGACY", "موروث"),
                            ("MANUAL", "يدوي"),
                            ("GUIDE", "دليل"),
                            ("ASSIGNMENT", "تكليف"),
                            ("LOCAL", "محلي"),
                        ],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="المصدر الأصلي",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("UNANSWERED", "غير محدد"),
                            ("COMPLIANT", "مطابق"),
                            ("NON_COMPLIANT", "غير مطابق"),
                            ("NOT_APPLICABLE", "غير منطبق"),
                        ],
                        default="UNANSWERED",
                        max_length=20,
                        verbose_name="النتيجة",
                    ),
                ),
                (
                    "value_text",
                    models.TextField(blank=True, verbose_name="القيمة / النص للمواصفة"),
                ),
                ("observation", models.TextField(blank=True, verbose_name="الملاحظات")),
                (
                    "is_local",
                    models.BooleanField(
                        default=False, verbose_name="محتوى محلي للزيارة"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inspection.visit",
                        verbose_name="الزيارة",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر زيارة",
                "verbose_name_plural": "عناصر الزيارة",
                "ordering": ["order", "created_at"],
                "unique_together": {("visit", "node_id")},
            },
        ),
    ]
